/**:
  ros__parameters:
    uav_parameters:
      mass: 2.064                  # Kg (base + rotors)
      arm_length: 0.25             # m
      num_of_arms: 4
      inertia:                     # Kg.m^2
        # ixx: 0.08612 # D'origine
        # iyy: 0.08962
        # izz: 0.16088
        ixx: 0.0216
        iyy: 0.0216
        izz: 0.040
        ixy: 0.0
        ixz: 0.0
        iyz: 0.0
      moment_constant: 0.016     # m
      thrust_constant: 8.54858e-06   # N.s^2/rad^2
      gravity: 9.81                # m/s^2
      pitch_trim_deg: 0.0          # x500 quadrotor mounting is level, no trim needed
      omega_to_pwm_coefficient:
        x_2: 0.001142
        x_1: 0.2273
        x_0: 914.2
      PWM_MIN: 1075
      PWM_MAX: 1950
      SIM_GZ_EC_MAX: 1000        # rad/s, corresponds to SIM_GZ_EC_MAX from PX4 parameters
      SIM_GZ_EC_MIN: 150         # rad/s, corresponds to SIM_GZ_EC_MIN from PX4 parameters
    landing_parameters:
      camera_frame_id: "x500_mono_cam_0/camera_link/imager"
      platform_frame_id: "platform"
      world_frame_id: "world"
      camera_offset_body:        # position of camera in body frame [m]
        x: 0.0
        y: 0.0
        z: -0.1